import { hubspotFormsRegistry } from "@/data/forms/hubspotFormsRegistry";
import { HubSpotConfigurationError } from "./hubspotErrors";

/**
 * Validates that the requested service has a valid HubSpot mapping in the registry.
 */
export function validateServiceFormContract(serviceKey) {
  const formConfig = hubspotFormsRegistry[serviceKey];
  if (!formConfig) {
    throw new HubSpotConfigurationError(
      `HubSpot Contract Violation: No form mapping found for service '${serviceKey}'`,
      { serviceKey }
    );
  }

  if (!formConfig.formId || !formConfig.portalId || !formConfig.region) {
    throw new HubSpotConfigurationError(
      `HubSpot Contract Violation: Incomplete form configuration for '${serviceKey}'`,
      { formConfig }
    );
  }

  return formConfig;
}

/**
 * Verifies that the payload generated by the builder does not contain unexpected fields
 * or miss required configuration constraints.
 * In a full enterprise environment with a PAT, this could also fetch the live schema from HubSpot API.
 */
export function validatePayloadContract(serviceKey, payload) {
  const config = validateServiceFormContract(serviceKey);

  // Surface mismatches between the generated payload and the registry constraints
  if (config.requiresFileUpload && !payload.fields.some((f) => f.name === "file_upload")) {
    // Note: just an example of a structural check; update based on real requirements
    console.warn(`[Contract Warning] Form ${serviceKey} requires file upload but no file field was provided.`);
  }

  // Validate the actual structure of the payload to be sent to HubSpot's submission API
  if (!payload || !Array.isArray(payload.fields)) {
    throw new HubSpotConfigurationError("HubSpot Contract Violation: Invalid payload structure generated.", { payload });
  }

  return true;
}
